export const songs = [
  { artist: "The Beatles", album: "Please Please Me", title: "I Saw Her Standing There", year: 1963, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Misery", year: 1963, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Anna (Go to Him)", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Chains", year: 1963, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Boys" , year: 1963, leadVocals:	["Ringo"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Ask Me Why", year: 1963, leadVocals:	["John"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Please Please Me", year: 1963, leadVocals:	["John", "Paul"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Love Me Do", year: 1963, leadVocals:	["John", "Paul"] },
  { artist: "The Beatles", album: "Please Please Me", title: "P.S. I Love You", year: 1963, leadVocals:["Paul"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Baby It's You", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Do You Want to Know a Secret", year: 1963, leadVocals:	["George"] },
  { artist: "The Beatles", album: "Please Please Me", title: "A Taste of Honey", year: 1963, leadVocals:	["Paul"] },
  { artist: "The Beatles", album: "Please Please Me", title: "There's a Place", year: 1963, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Please Please Me", title: "Twist and Shout", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", title: "It Won't Be Long", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", title: "All I've Got to Do", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", title: "All My Loving", year: 1963, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Don't Bother Me", year: 1963, leadVocals: ["George"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Little Child", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Till There Was You", year: 1963, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Please Mister Postman", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Roll Over Beethoven", year: 1963, leadVocals: ["George"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Hold Me Tight", year: 1963, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "With the Beatles", title: "You Really Got a Hold on Me", year: 1963, leadVocals: ["John", "George"] },
  { artist: "The Beatles", album: "With the Beatles", title: "I Wanna Be Your Man", year: 1963, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Devil in Her Heart", year: 1963, leadVocals: ["George"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Not a Second Time", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", title: "Money (That's What I Want)", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "A Hard Day's Night", year: 1964, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "I Should Have Known Better", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "If I Fell", year: 1964, leadVocals: ["John, Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "I'm Happy Just to Dance with You", year: 1964, leadVocals: ["George"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "And I Love Her", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "Tell Me Why", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "Can't Buy Me Love", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "Any Time at All", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "I'll Cry Instead", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "Things We Said Today", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "When I Get Home", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "You Can't Do That", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", title: "I'll Be Back", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "No Reply", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "I'm a Loser", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Baby's in Black", year: 1964, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Rock and Roll Music", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "I'll Follow the Sun", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Mr. Moonlight", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Kansas City/Hey, Hey, Hey, Hey", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Eight Days a Week", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Words of Love", year: 1964, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Honey Don't", year: 1964, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Every Little Thing", year: 1964, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "I Don't Want to Spoil the Party", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "What You're Doing", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", title: "Everybody's Trying to Be My Baby", year: 1964, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Help!", title: "Help!", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", title: "The Night Before", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Help!", title: "You've Got to Hide Your Love Away", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", title: "I Need You", year: 1965, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Help!", title: "Another Girl", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Help!", title: "You're Going to Lose That Girl", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", title: "Ticket to Ride", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", title: "Act Naturally", year: 1965, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Help!", title: "It's Only Love", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", title: "You Like Me Too Much", year: 1965, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Help!", title: "Tell Me What You See", year: 1965, leadVocals: ["Paul", "John"] },
  { artist: "The Beatles", album: "Help!", title: "I've Just Seen a Face", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Help!", title: "Yesterday", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Help!", title: "Dizzy Miss Lizzy", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "Drive My Car", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "Norwegian Wood (This Bird Has Flown)", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "You Won't See Me", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "Nowhere Man", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "Think for Yourself", year: 1965, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "The Word", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "Michelle", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "What Goes On", year: 1965, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "Girl", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "I'm Looking Through You", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "In My Life", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "Wait", year: 1965, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "If I Needed Someone", year: 1965, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Rubber Soul", title: "Run for Your Life", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", title: "Taxman", year: 1966, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Revolver", title: "Eleanor Rigby", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", title: "I'm Only Sleeping", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", title: "Love You To", year: 1966, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Revolver", title: "Here, There and Everywhere", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", title: "Yellow Submarine", year: 1966, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Revolver", title: "She Said She Said", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", title: "Good Day Sunshine", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", title: "And Your Bird Can Sing", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", title: "For No One", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", title: "Doctor Robert", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", title: "I Want to Tell You", year: 1966, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Revolver", title: "Got to Get You into My Life", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", title: "Tomorrow Never Knows", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Sgt. Pepper's Lonely Hearts Club Band", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "With a Little Help from My Friends", year: 1967, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Lucy in the Sky with Diamonds", year: 1967, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Getting Better", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Fixing a Hole", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "She's Leaving Home", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Being for the Benefit of Mr. Kite!", year: 1967, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Within You Without You", year: 1967, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "When I'm Sixty-Four", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Lovely Rita", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Good Morning Good Morning", year: 1967, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "Sgt. Pepper's Lonely Hearts Club Band (Reprise)", year: 1967, leadVocals: ["John", "Paul", "George"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", title: "A Day in the Life", year: 1967, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Back in the U.S.S.R.", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Dear Prudence", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Glass Onion", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Ob-La-Di, Ob-La-Da", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Wild Honey Pie", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "The Continuing Story of Bungalow Bill", leadVocals: ["John"	] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "While My Guitar Gently Weeps", leadVocals: ["George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Happiness Is a Warm Gun", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Martha My Dear", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "I'm So Tired", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Blackbird", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Piggies", leadVocals: ["George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Rocky Raccoon", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Don't Pass Me By", leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Why Don't We Do It in the Road?", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "I Will", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Julia", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Birthday", leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Yer Blues", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Mother Nature's Son", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Everybody's Got Something to Hide Except Me and My Monkey", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Sexy Sadie", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Helter Skelter", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Long, Long, Long", leadVocals: ["George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Revolution 1", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Honey Pie", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Savoy Truffle", leadVocals: ["George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Cry Baby Cry", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Revolution 9", leadVocals: ["John", "George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, title: "Good Night", leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Yellow Submarine", leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Only a Northern Song", leadVocals: ["George"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "All Together Now", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Hey Bulldog", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "It's All Too Much", leadVocals: ["George"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "All You Need Is Love", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Pepperland", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Sea of Time", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Sea of Holes", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Sea of Monsters", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "March of the Meanies", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Pepperland Laid Waste", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, title: "Yellow Submarine in Pepperland", leadVocals: [] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Come Together", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Something", leadVocals: ["George"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Maxwell's Silver Hammer", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Oh! Darling", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Octopus's Garden", leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "I Want You (She's So Heavy)", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Here Comes the Sun", leadVocals: ["George"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Because", leadVocals: ["John", "Paul", "George"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "You Never Give Me Your Money", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Sun King", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Mean Mr. Mustard", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Polythene Pam", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "She Came in Through the Bathroom Window", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Golden Slumbers", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Carry That Weight", leadVocals: ["Paul", "John", "George", "Ringo"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "The End", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, title: "Her Majesty", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Let it Be", title: "Two of Us", year: 1970, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Let it Be", title: "Dig a Pony", year: 1970, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Let it Be", title: "Across the Universe", year: 1970, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Let it Be", title: "I Me Mine", year: 1970, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Let it Be", title: "Dig It", year: 1970, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Let it Be", title: "Let It Be", year: 1970, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Let it Be", title: "Maggie Mae", year: 1970, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Let it Be", title: "I've Got a Feeling", year: 1970, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Let it Be", title: "One After 909", year: 1970, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Let it Be", title: "The Long and Winding Road", year: 1970, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Let it Be", title: "For You Blue", year: 1970, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Let it Be", title: "Get Back", year: 1970, leadVocals: ["Paul"] }
]
