export const albums = [
  { artist: "The Beatles", album: "Please Please Me", song: "I Saw Her Standing There", year: 1963, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Misery", year: 1963, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Anna (Go to Him)", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Chains", year: 1963, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Boys" , year: 1963, leadVocals:	["Ringo"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Ask Me Why", year: 1963, leadVocals:	["John"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Please Please Me", year: 1963, leadVocals:	["John", "Paul"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Love Me Do", year: 1963, leadVocals:	["John", "Paul"] },
  { artist: "The Beatles", album: "Please Please Me", song: "P.S. I Love You", year: 1963, leadVocals:["Paul"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Baby It's You", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Do You Want to Know a Secret", year: 1963, leadVocals:	["George"] },
  { artist: "The Beatles", album: "Please Please Me", song: "A Taste of Honey", year: 1963, leadVocals:	["Paul"] },
  { artist: "The Beatles", album: "Please Please Me", song: "There's a Place", year: 1963, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Please Please Me", song: "Twist and Shout", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", song: "It Won't Be Long", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", song: "All I've Got to Do", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", song: "All My Loving", year: 1963, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Don't Bother Me", year: 1963, leadVocals: ["George"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Little Child", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Till There Was You", year: 1963, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Please Mister Postman", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Roll Over Beethoven", year: 1963, leadVocals: ["George"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Hold Me Tight", year: 1963, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "With the Beatles", song: "You Really Got a Hold on Me", year: 1963, leadVocals: ["John", "George"] },
  { artist: "The Beatles", album: "With the Beatles", song: "I Wanna Be Your Man", year: 1963, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Devil in Her Heart", year: 1963, leadVocals: ["George"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Not a Second Time", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "With the Beatles", song: "Money (That's What I Want)", year: 1963, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "A Hard Day's Night", year: 1964, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "I Should Have Known Better", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "If I Fell", year: 1964, leadVocals: ["John, Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "I'm Happy Just to Dance with You", year: 1964, leadVocals: ["George"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "And I Love Her", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "Tell Me Why", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "Can't Buy Me Love", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "Any Time at All", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "I'll Cry Instead", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "Things We Said Today", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "When I Get Home", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "You Can't Do That", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "A Hard Day's Night", song: "I'll Be Back", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "No Reply", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "I'm a Loser", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Baby's in Black", year: 1964, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Rock and Roll Music", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "I'll Follow the Sun", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Mr. Moonlight", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Kansas City/Hey, Hey, Hey, Hey", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Eight Days a Week", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Words of Love", year: 1964, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Honey Don't", year: 1964, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Every Little Thing", year: 1964, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "I Don't Want to Spoil the Party", year: 1964, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "What You're Doing", year: 1964, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Beatles for Sale", song: "Everybody's Trying to Be My Baby", year: 1964, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Help!", song: "Help!", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", song: "The Night Before", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Help!", song: "You've Got to Hide Your Love Away", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", song: "I Need You", year: 1965, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Help!", song: "Another Girl", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Help!", song: "You're Going to Lose That Girl", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", song: "Ticket to Ride", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", song: "Act Naturally", year: 1965, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Help!", song: "It's Only Love", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Help!", song: "You Like Me Too Much", year: 1965, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Help!", song: "Tell Me What You See", year: 1965, leadVocals: ["Paul", "John"] },
  { artist: "The Beatles", album: "Help!", song: "I've Just Seen a Face", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Help!", song: "Yesterday", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Help!", song: "Dizzy Miss Lizzy", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "I've Just Seen a Face", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "Norwegian Wood (This Bird Has Flown)", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "You Won't See Me", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "Think for Yourself", year: 1965, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "The Word", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "Michelle", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "It's Only Love", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "Girl", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "I'm Looking Through You", year: 1965, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "In My Life", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "Wait", year: 1965, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Rubber Soul", song: "Run for Your Life", year: 1965, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", song: "Taxman", year: 1966, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Revolver", song: "Eleanor Rigby", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", song: "I'm Only Sleeping", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", song: "Love You To", year: 1966, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Revolver", song: "Here, There and Everywhere", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", song: "Yellow Submarine", year: 1966, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Revolver", song: "She Said She Said", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", song: "Good Day Sunshine", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", song: "And Your Bird Can Sing", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", song: "For No One", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", song: "Doctor Robert", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Revolver", song: "I Want to Tell You", year: 1966, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Revolver", song: "Got to Get You into My Life", year: 1966, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Revolver", song: "Tomorrow Never Knows", year: 1966, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Sgt. Pepper's Lonely Hearts Club Band", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "With a Little Help from My Friends", year: 1967, leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Lucy in the Sky with Diamonds", year: 1967, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Getting Better", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Fixing a Hole", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "She's Leaving Home", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Being for the Benefit of Mr. Kite!", year: 1967, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Within You Without You", year: 1967, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "When I'm Sixty-Four", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Lovely Rita", year: 1967, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Good Morning Good Morning", year: 1967, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", song: "Sgt. Pepper's Lonely Hearts Club Band (Reprise)", year: 1967, leadVocals: ["John", "Paul", "George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "A Day in the Life", leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Back in the U.S.S.R.", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Dear Prudence", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Glass Onion", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Ob-La-Di, Ob-La-Da", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Wild Honey Pie", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "The Continuing Story of Bungalow Bill", leadVocals: ["John"	] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "While My Guitar Gently Weeps", leadVocals: ["George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Happiness Is a Warm Gun", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Martha My Dear", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "I'm So Tired", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Blackbird", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Piggies", leadVocals: ["George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Rocky Raccoon", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Don't Pass Me By", leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Why Don't We Do It in the Road?", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "I Will", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Julia", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Birthday", leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Yer Blues", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Mother Nature's Son", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Everybody's Got Something to Hide Except Me and My Monkey", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Sexy Sadie", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Helter Skelter", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Long, Long, Long", leadVocals: ["George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Revolution 1", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Honey Pie", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Savoy Truffle", leadVocals: ["George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Cry Baby Cry", leadVocals: ["John"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Revolution 9", leadVocals: ["John", "George"] },
  { artist: "The Beatles", album: "The Beatles", year: 1968, song: "Good Night", leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Yellow Submarine", leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Only a Northern Song", leadVocals: ["George"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "All Together Now", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Hey Bulldog", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "It's All Too Much", leadVocals: ["George"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "All You Need Is Love", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Pepperland", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Sea of Time", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Sea of Holes", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Sea of Monsters", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "March of the Meanies", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Pepperland Laid Waste", leadVocals: [] },
  { artist: "The Beatles", album: "Yellow Submarine", year: 1969, song: "Yellow Submarine in Pepperland", leadVocals: [] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Come Together", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Something", leadVocals: ["George"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Maxwell's Silver Hammer", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Oh! Darling", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Octopus's Garden", leadVocals: ["Ringo"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "I Want You (She's So Heavy)", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Here Comes the Sun", leadVocals: ["George"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Because", leadVocals: ["John", "Paul", "George"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "You Never Give Me Your Money", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Sun King", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Mean Mr. Mustard", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Polythene Pam", leadVocals: ["John"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "She Came in Through the Bathroom Window", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Golden Slumbers", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Carry That Weight", leadVocals: ["Paul", "John", "George", "Ringo"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "The End", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Abbey Road", year: 1969, song: "Her Majesty", leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Let it Be", song: "Two of Us", year: 1970, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Let it Be", song: "Dig a Pony", year: 1970, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Let it Be", song: "Across the Universe", year: 1970, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Let it Be", song: "I Me Mine", year: 1970, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Let it Be", song: "Dig It", year: 1970, leadVocals: ["John"] },
  { artist: "The Beatles", album: "Let it Be", song: "Let It Be", year: 1970, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Let it Be", song: "Maggie Mae", year: 1970, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Let it Be", song: "I've Got a Feeling", year: 1970, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Let it Be", song: "One After 909", year: 1970, leadVocals: ["John", "Paul"] },
  { artist: "The Beatles", album: "Let it Be", song: "The Long and Winding Road", year: 1970, leadVocals: ["Paul"] },
  { artist: "The Beatles", album: "Let it Be", song: "For You Blue", year: 1970, leadVocals: ["George"] },
  { artist: "The Beatles", album: "Let it Be", song: "Get Back", year: 1970, leadVocals: ["Paul"] }
]
